################################################################################
# :dets.add_user                                        #                     /3
# :dets.all                                             #                     /0
# :dets.bchunk                                          #                     /2
# :dets.close                                           #                     /1
# :dets.delete                                          #                     /2
# :dets.delete_all_objects                              #                     /1
# :dets.delete_object                                   #                     /2
# :dets.file_info                                       #                     /1
# :dets.first                                           #                     /1
# :dets.foldl                                           #                     /3
# :dets.foldr                                           #                     /3
# :dets.from_ets                                        #                     /2
# :dets.fsck                                            #                     /1
# :dets.fsck                                            #                     /2
# :dets.get_head_field                                  #                     /2
# :dets.info                                            #                     /1
# :dets.info                                            #                     /2
# :dets.init                                            #                     /2
# :dets.init_table                                      #                     /2
# :dets.init_table                                      #                     /3
# :dets.insert                                          #                     /2
# :dets.insert_new                                      #                     /2
# :dets.internal_close                                  #                     /1
# :dets.internal_open                                   #                     /3
# :dets.is_compatible_bchunk_format                     #                     /2
# :dets.is_dets_file                                    #                     /1
# :dets.istart_link                                     #                     /1
# :dets.lookup                                          #                     /2
# :dets.lookup_keys                                     #                     /2
# :dets.match                                           #                     /1
# :dets.match                                           #                     /2
# :dets.match                                           #                     /3
# :dets.match_delete                                    #                     /2
# :dets.match_object                                    #                     /1
# :dets.match_object                                    #                     /2
# :dets.match_object                                    #                     /3
# :dets.member                                          #                     /2
# :dets.module_info                                     #                     /0
# :dets.module_info                                     #                     /1
# :dets.next                                            #                     /2
# :dets.open_file                                       #                     /1
# :dets.open_file                                       #                     /2
# :dets.pid2name                                        #                     /1
# :dets.remove_user                                     #                     /2
# :dets.repair_continuation                             #                     /2
# :dets.safe_fixtable                                   #                     /2
# :dets.select                                          #                     /1
# :dets.select                                          #                     /2
# :dets.select                                          #                     /3
# :dets.select_delete                                   #                     /2
# :dets.slot                                            #                     /2
# :dets.start                                           #                     /0
# :dets.stop                                            #                     /0
# :dets.sync                                            #                     /1
# :dets.system_code_change                              #                     /4
# :dets.system_continue                                 #                     /3
# :dets.system_terminate                                #                     /4
# :dets.table                                           #                     /1
# :dets.table                                           #                     /2
# :dets.to_ets                                          #                     /2
# :dets.traverse                                        #                     /2
# :dets.update_counter                                  #                     /3
# :dets.verbose                                         #                     /0
# :dets.verbose                                         #                     /1
# :dets.view                                            #                     /1
# :dets.where                                           #                     /2
#-------------------------------------------------------#----------------------#
# :dets_server.all                                      #                     /0
# :dets_server.close                                    #                     /1
# :dets_server.code_change                              #                     /3
# :dets_server.get_pid                                  #                     /1
# :dets_server.handle_call                              #                     /3
# :dets_server.handle_cast                              #                     /2
# :dets_server.handle_info                              #                     /2
# :dets_server.init                                     #                     /1
# :dets_server.module_info                              #                     /0
# :dets_server.module_info                              #                     /1
# :dets_server.open_file                                #                     /1
# :dets_server.open_file                                #                     /2
# :dets_server.pid2name                                 #                     /1
# :dets_server.start                                    #                     /0
# :dets_server.start_link                               #                     /0
# :dets_server.stop                                     #                     /0
# :dets_server.terminate                                #                     /2
# :dets_server.users                                    #                     /1
# :dets_server.verbose                                  #                     /1
#-------------------------------------------------------#----------------------#
# :dets_sup.init                                        #                     /1
# :dets_sup.module_info                                 #                     /0
# :dets_sup.module_info                                 #                     /1
# :dets_sup.start_link                                  #                     /0
#-------------------------------------------------------#----------------------#
# :dets_utils.all_allocated                             #                     /1
# :dets_utils.all_allocated_as_list                     #                     /1
# :dets_utils.all_free                                  #                     /1
# :dets_utils.alloc                                     #                     /2
# :dets_utils.alloc_many                                #                     /4
# :dets_utils.bad_object                                #                     /2
# :dets_utils.cache_lookup                              #                     /4
# :dets_utils.cache_size                                #                     /1
# :dets_utils.cmp                                       #                     /2
# :dets_utils.code_to_type                              #                     /1
# :dets_utils.corrupt                                   #                     /2
# :dets_utils.corrupt_file                              #                     /2
# :dets_utils.corrupt_reason                            #                     /2
# :dets_utils.debug_mode                                #                     /0
# :dets_utils.disk_map_segment                          #                     /2
# :dets_utils.disk_map_segment_p                        #                     /2
# :dets_utils.empty_free_lists                          #                     /0
# :dets_utils.family                                    #                     /1
# :dets_utils.file_error                                #                     /2
# :dets_utils.find_allocated                            #                     /4
# :dets_utils.find_next_allocated                       #                     /3
# :dets_utils.free                                      #                     /3
# :dets_utils.fwrite                                    #                     /3
# :dets_utils.get_freelists                             #                     /1
# :dets_utils.init_alloc                                #                     /1
# :dets_utils.init_disk_map                             #                     /1
# :dets_utils.ipread                                    #                     /3
# :dets_utils.is_empty_cache                            #                     /1
# :dets_utils.list_to_tree                              #                     /1
# :dets_utils.log2                                      #                     /1
# :dets_utils.make_zeros                                #                     /1
# :dets_utils.mkeysearch                                #                     /3
# :dets_utils.mkeysort                                  #                     /2
# :dets_utils.module_info                               #                     /0
# :dets_utils.module_info                               #                     /1
# :dets_utils.msort                                     #                     /1
# :dets_utils.new_cache                                 #                     /1
# :dets_utils.open                                      #                     /2
# :dets_utils.position                                  #                     /2
# :dets_utils.position                                  #                     /3
# :dets_utils.position_close                            #                     /3
# :dets_utils.pread                                     #                     /2
# :dets_utils.pread                                     #                     /4
# :dets_utils.pread_close                               #                     /4
# :dets_utils.pread_n                                   #                     /3
# :dets_utils.pwrite                                    #                     /2
# :dets_utils.pwrite                                    #                     /3
# :dets_utils.read_4                                    #                     /2
# :dets_utils.read_n                                    #                     /2
# :dets_utils.rename                                    #                     /2
# :dets_utils.reset_cache                               #                     /1
# :dets_utils.stop_disk_map                             #                     /0
# :dets_utils.sync                                      #                     /1
# :dets_utils.tree_to_bin                               #                     /5
# :dets_utils.truncate                                  #                     /2
# :dets_utils.truncate                                  #                     /3
# :dets_utils.type_to_code                              #                     /1
# :dets_utils.vformat                                   #                     /2
# :dets_utils.write                                     #                     /2
# :dets_utils.write_file                                #                     /2
#-------------------------------------------------------#----------------------#
# :dets_v9.bchunk_init                                  #                     /2
# :dets_v9.bulk_input                                   #                     /3
# :dets_v9.cache_segps                                  #                     /3
# :dets_v9.check_file_header                            #                     /2
# :dets_v9.compact_init                                 #                     /3
# :dets_v9.db_hash                                      #                     /2
# :dets_v9.do_perform_save                              #                     /1
# :dets_v9.file_info                                    #                     /1
# :dets_v9.find_object                                  #                     /2
# :dets_v9.fsck_input                                   #                     /4
# :dets_v9.init_freelist                                #                     /1
# :dets_v9.initiate_file/                               #                     11
# :dets_v9.mark_dirty                                   #                     /1
# :dets_v9.may_grow                                     #                     /3
# :dets_v9.module_info                                  #                     /0
# :dets_v9.module_info                                  #                     /1
# :dets_v9.no_slots                                     #                     /1
# :dets_v9.output_objs                                  #                     /3
# :dets_v9.prep_table_copy                              #                     /9
# :dets_v9.read_bchunks                                 #                     /2
# :dets_v9.read_file_header                             #                     /2
# :dets_v9.scan_objs                                    #                     /8
# :dets_v9.slot_objs                                    #                     /2
# :dets_v9.table_parameters                             #                     /1
# :dets_v9.try_bchunk_header                            #                     /2
# :dets_v9.v_segments                                   #                     /1
# :dets_v9.write_cache                                  #                     /1
################################################################################
# :dict.append                                          #                     /3
# :dict.append_list                                     #                     /3
# :dict.erase                                           #                     /2
# :dict.fetch                                           #                     /2
# :dict.fetch_keys                                      #                     /1
# :dict.filter                                          #                     /2
# :dict.find                                            #                     /2
# :dict.fold                                            #                     /3
# :dict.from_list                                       #                     /1
# :dict.is_empty                                        #                     /1
# :dict.is_key                                          #                     /2
# :dict.map                                             #                     /2
# :dict.merge                                           #                     /3
# :dict.module_info                                     #                     /0
# :dict.module_info                                     #                     /1
# :dict.new                                             #                     /0
# :dict.size                                            #                     /1
# :dict.store                                           #                     /3
# :dict.take                                            #                     /2
# :dict.to_list                                         #                     /1
# :dict.update                                          #                     /3
# :dict.update                                          #                     /4
# :dict.update_counter                                  #                     /3
################################################################################
# :digraph.add_edge                                     #                     /3
# :digraph.add_edge                                     #                     /4
# :digraph.add_edge                                     #                     /5
# :digraph.add_vertex                                   #                     /1
# :digraph.add_vertex                                   #                     /2
# :digraph.add_vertex                                   #                     /3
# :digraph.del_edge                                     #                     /2
# :digraph.del_edges                                    #                     /2
# :digraph.del_path                                     #                     /3
# :digraph.del_vertex                                   #                     /2
# :digraph.del_vertices                                 #                     /2
# :digraph.delete                                       #                     /1
# :digraph.edge                                         #                     /2
# :digraph.edges                                        #                     /1
# :digraph.edges                                        #                     /2
# :digraph.get_cycle                                    #                     /2
# :digraph.get_path                                     #                     /3
# :digraph.get_short_cycle                              #                     /2
# :digraph.get_short_path                               #                     /3
# :digraph.in_degree                                    #                     /2
# :digraph.in_edges                                     #                     /2
# :digraph.in_neighbours                                #                     /2
# :digraph.info                                         #                     /1
# :digraph.module_info                                  #                     /0
# :digraph.module_info                                  #                     /1
# :digraph.new                                          #                     /0
# :digraph.new                                          #                     /1
# :digraph.no_edges                                     #                     /1
# :digraph.no_vertices                                  #                     /1
# :digraph.out_degree                                   #                     /2
# :digraph.out_edges                                    #                     /2
# :digraph.out_neighbours                               #                     /2
# :digraph.sink_vertices                                #                     /1
# :digraph.source_vertices                              #                     /1
# :digraph.vertex                                       #                     /2
# :digraph.vertices                                     #                     /1
#-------------------------------------------------------#----------------------#
# :digraph_utils.arborescence_root                      #                     /1
# :digraph_utils.components                             #                     /1
# :digraph_utils.condensation                           #                     /1
# :digraph_utils.cyclic_strong_components               #                     /1
# :digraph_utils.is_acyclic                             #                     /1
# :digraph_utils.is_arborescence                        #                     /1
# :digraph_utils.is_tree                                #                     /1
# :digraph_utils.loop_vertices                          #                     /1
# :digraph_utils.module_info                            #                     /0
# :digraph_utils.module_info                            #                     /1
# :digraph_utils.postorder                              #                     /1
# :digraph_utils.preorder                               #                     /1
# :digraph_utils.reachable                              #                     /2
# :digraph_utils.reachable_neighbours                   #                     /2
# :digraph_utils.reaching                               #                     /2
# :digraph_utils.reaching_neighbours                    #                     /2
# :digraph_utils.strong_components                      #                     /1
# :digraph_utils.subgraph                               #                     /2
# :digraph_utils.subgraph                               #                     /3
# :digraph_utils.topsort                                #                     /1
################################################################################
# :disk_log.accessible_logs                             #                     /0
# :disk_log.alog                                        #                     /2
# :disk_log.alog_terms                                  #                     /2
# :disk_log.balog                                       #                     /2
# :disk_log.balog_terms                                 #                     /2
# :disk_log.bchunk                                      #                     /2
# :disk_log.bchunk                                      #                     /3
# :disk_log.block                                       #                     /1
# :disk_log.block                                       #                     /2
# :disk_log.blog                                        #                     /2
# :disk_log.blog_terms                                  #                     /2
# :disk_log.breopen                                     #                     /3
# :disk_log.btruncate                                   #                     /2
# :disk_log.change_header                               #                     /2
# :disk_log.change_notify                               #                     /3
# :disk_log.change_size                                 #                     /2
# :disk_log.chunk                                       #                     /2
# :disk_log.chunk                                       #                     /3
# :disk_log.chunk_info                                  #                     /1
# :disk_log.chunk_step                                  #                     /3
# :disk_log.close                                       #                     /1
# :disk_log.do_info                                     #                     /2
# :disk_log.do_log                                      #                     /2
# :disk_log.do_sync                                     #                     /1
# :disk_log.format_error                                #                     /1
# :disk_log.ichunk_end                                  #                     /2
# :disk_log.inc_wrap_file                               #                     /1
# :disk_log.info                                        #                     /1
# :disk_log.init                                        #                     /2
# :disk_log.internal_open                               #                     /2
# :disk_log.istart_link                                 #                     /1
# :disk_log.lclose                                      #                     /1
# :disk_log.lclose                                      #                     /2
# :disk_log.ll_close                                    #                     /1
# :disk_log.ll_open                                     #                     /1
# :disk_log.log                                         #                     /2
# :disk_log.log_terms                                   #                     /2
# :disk_log.module_info                                 #                     /0
# :disk_log.module_info                                 #                     /1
# :disk_log.open                                        #                     /1
# :disk_log.pid2name                                    #                     /1
# :disk_log.reopen                                      #                     /2
# :disk_log.reopen                                      #                     /3
# :disk_log.start                                       #                     /0
# :disk_log.sync                                        #                     /1
# :disk_log.system_code_change                          #                     /4
# :disk_log.system_continue                             #                     /3
# :disk_log.system_terminate                            #                     /4
# :disk_log.truncate                                    #                     /1
# :disk_log.truncate                                    #                     /2
#-------------------------------------------------------#----------------------#
# :disk_log_1.change_size_wrap                          #                     /3
# :disk_log_1.chunk                                     #                     /5
# :disk_log_1.chunk_read_only                           #                     /5
# :disk_log_1.close                                     #                     /3
# :disk_log_1.ext_open                                  #                     /4
# :disk_log_1.fclose                                    #                     /2
# :disk_log_1.fwrite                                    #                     /4
# :disk_log_1.get_wrap_size                             #                     /1
# :disk_log_1.int_open                                  #                     /4
# :disk_log_1.is_head                                   #                     /1
# :disk_log_1.is_quiet                                  #                     /0
# :disk_log_1.logl                                      #                     /1
# :disk_log_1.mf_ext_close                              #                     /2
# :disk_log_1.mf_ext_inc                                #                     /2
# :disk_log_1.mf_ext_log                                #                     /3
# :disk_log_1.mf_ext_open                               #                     /7
# :disk_log_1.mf_int_chunk                              #                     /4
# :disk_log_1.mf_int_chunk_read_only                    #                     /4
# :disk_log_1.mf_int_chunk_step                         #                     /3
# :disk_log_1.mf_int_close                              #                     /2
# :disk_log_1.mf_int_inc                                #                     /2
# :disk_log_1.mf_int_log                                #                     /3
# :disk_log_1.mf_int_open                               #                     /7
# :disk_log_1.mf_sync                                   #                     /1
# :disk_log_1.mf_write_cache                            #                     /1
# :disk_log_1.module_info                               #                     /0
# :disk_log_1.module_info                               #                     /1
# :disk_log_1.position                                  #                     /3
# :disk_log_1.print_index_file                          #                     /1
# :disk_log_1.read_index_file                           #                     /1
# :disk_log_1.read_size_file                            #                     /1
# :disk_log_1.read_size_file_version                    #                     /1
# :disk_log_1.set_quiet                                 #                     /1
# :disk_log_1.sync                                      #                     /2
# :disk_log_1.truncate                                  #                     /3
# :disk_log_1.truncate_at                               #                     /3
# :disk_log_1.write_cache                               #                     /2
#-------------------------------------------------------#----------------------#
# :disk_log_server.accessible_logs                      #                     /0
# :disk_log_server.close                                #                     /1
# :disk_log_server.code_change                          #                     /3
# :disk_log_server.dist_open                            #                     /1
# :disk_log_server.get_local_pid                        #                     /1
# :disk_log_server.get_log_pids                         #                     /1
# :disk_log_server.handle_call                          #                     /3
# :disk_log_server.handle_cast                          #                     /2
# :disk_log_server.handle_info                          #                     /2
# :disk_log_server.init                                 #                     /1
# :disk_log_server.module_info                          #                     /0
# :disk_log_server.module_info                          #                     /1
# :disk_log_server.open                                 #                     /1
# :disk_log_server.start                                #                     /0
# :disk_log_server.start_link                           #                     /0
# :disk_log_server.terminate                            #                     /2
#-------------------------------------------------------#----------------------#
# :disk_log_sup.init                                    #                     /1
# :disk_log_sup.module_info                             #                     /0
# :disk_log_sup.module_info                             #                     /1
# :disk_log_sup.start_link                              #                     /0
################################################################################
# :dist_ac.code_change                                  #                     /3
# :dist_ac.get_known_nodes                              #                     /0
# :dist_ac.handle_call                                  #                     /3
# :dist_ac.handle_cast                                  #                     /2
# :dist_ac.handle_info                                  #                     /2
# :dist_ac.info                                         #                     /0
# :dist_ac.init                                         #                     /1
# :dist_ac.load_application                             #                     /2
# :dist_ac.module_info                                  #                     /0
# :dist_ac.module_info                                  #                     /1
# :dist_ac.permit_application                           #                     /2
# :dist_ac.permit_only_loaded_application               #                     /2
# :dist_ac.send_timeout                                 #                     /3
# :dist_ac.start_link                                   #                     /0
# :dist_ac.takeover_application                         #                     /2
# :dist_ac.terminate                                    #                     /2
#-------------------------------------------------------#----------------------#
# :dist_util.cancel_timer                               #                     /1
# :dist_util.handshake_other_started                    #                     /1
# :dist_util.handshake_we_started                       #                     /1
# :dist_util.module_info                                #                     /0
# :dist_util.module_info                                #                     /1
# :dist_util.reset_timer                                #                     /1
# :dist_util.setup_timer                                #                     /2
# :dist_util.shutdown                                   #                     /3
# :dist_util.shutdown                                   #                     /4
# :dist_util.start_timer                                #                     /1
################################################################################
# :edlin.current_chars                                  #                     /1
# :edlin.current_line                                   #                     /1
# :edlin.edit_line                                      #                     /2
# :edlin.edit_line1                                     #                     /2
# :edlin.erase_inp                                      #                     /1
# :edlin.erase_line                                     #                     /1
# :edlin.init                                           #                     /0
# :edlin.init                                           #                     /1
# :edlin.length_after                                   #                     /1
# :edlin.length_before                                  #                     /1
# :edlin.module_info                                    #                     /0
# :edlin.module_info                                    #                     /1
# :edlin.over_word                                      #                     /3
# :edlin.prefix_arg                                     #                     /1
# :edlin.prompt                                         #                     /1
# :edlin.redraw_line                                    #                     /1
# :edlin.start                                          #                     /1
# :edlin.start                                          #                     /2
#-------------------------------------------------------#----------------------#
# :edlin_expand.expand                                  #                     /1
# :edlin_expand.format_matches                          #                     /1
# :edlin_expand.module_info                             #                     /0
# :edlin_expand.module_info                             #                     /1
